unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-b
set -g mouse on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind %
bind t split-window -h -l 33% -c "#{pane_current_path}"
# bind t split-window -h -c "#{pane_current_path}"

unbind '"'
bind R split-window -v -l 33% -c "#{pane_current_path}"
# bind R split-window -v -c "#{pane_current_path}"

# new session
bind N command-prompt -p "New session name:" "new-session -s '%%'"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# set -g @plugin 'vaaleyard/tmux-dotbar'
# Since this theme does not display window indexes, it's best suited for users who manage a small number of windows.
# To improve usability, it's hugely recommended to enable automatic renumbering when windows are closed.
# Also a good option is to start window indexes at 1 for easier tracking.

set-option -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'vaaleyard/tmux-dotbar'

set -g @tmux-dotbar-fg "#0B0E14"
set -g @tmux-dotbar-bg "#475266"
set -g @tmux-dotbar-fg-current "#BFBDB6"
set -g @tmux-dotbar-fg-session "#565B66"
set -g @tmux-dotbar-fg-prefix "#95E6CB"
set -g @tmux-dotbar-position "bottom"
set -g @tmux-dotbar-justify "absolute-centre"
set -g @tmux-dotbar-left "false"
set -g @tmux-dotbar-status-left "#S" # see code
set -g @tmux-dotbar-right "false"
set -g @tmux-dotbar-status-right "%H:%M" # see code
set -g @tmux-dotbar-window-status-format " #W "
set -g @tmux-dotbar-window-status-separator " • "
set -g @tmux-dotbar-maximized-icon "󰊓"
set -g @tmux-dotbar-show-maximized-icon-for-all-tabs false
set -g @tmux-dotbar-bold-status true
set -g @tmux-dotbar-bold-current-window false
set -g @tmux-dotbar-bg "#1e1e2e"
set -g @tmux-dotbar-fg "#585b70"
set -g @tmux-dotbar-fg-current "#cdd6f4"
set -g @tmux-dotbar-fg-session "#9399b2"
set -g @tmux-dotbar-fg-prefix "#cba6f7"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

